---
name: Lingua-Strfname
version: 0.12
author:
  - |-
    David Wheeler <david@kineticode.com>, with implementation assistance from
    David Lowe.
abstract: Formats people's names
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  perl: 5.006
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Lingua::Strfname:
    file: lib/Lingua/Strfname.pm
    version: 0.12
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
